export const machineLabels = {
  chest_press: "Chest Press",
  lat_pull: "Lat Pull",
  leg_ext: "Leg Extension",
  seated_row: "Seated Row",
  seated_leg_curl: "seated Leg Curl",
  hip_abductor:"Hip Abductor",
  flat_bench_press: "Bench Press",
  incline_cable_curl: "Incline Curl",
  preacher_curl: "Preacher Curl",
  cable_fly: "Cable Fly",
  shoulder_press: "Shoulder Press",
  incline_press:"Incline Press",
  triceps_pushdown: "Triceps Pushdown",
  overhead_triceps_extension: "OH Triceps",
  cable_lateral_raise: "Cable Lateral Raise",
  seated_cable_row: "Cable Row",
  leg_press: "Leg Press",
  leg_extension: "Leg Extension",
  calf_raise:"Calf Raise",
  hip_adductor: "Hip Adductor",
  lat_pulldown: "Lat Pulldown",
};